language: node_js
node_js:
  - "6"
cache:
  - node_modules
install:
  - npm install
  - npm install -g eslint
  - npm install -g codecov
script:
  - eslint .
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - codecov

